entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443

providers:
  docker:
    exposedByDefault: false

serversTransport:
  maxIdleConnsPerHost: 0

certificatesResolvers:
  letsencrypt:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: {{your-email-address-here}}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http
